export const hairstylesList = [
  {
    category: "Braids",
    description:
      "(Knotless braids/Twists/Box braids). Be it plain braids/twist, with curls at the end or on the body, goddess or boho braids/twist any style as long as there's no weaving.",
    items: [
      {
        name: "Bob to shoulder length (small)",
        price: 15000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Bra to waist length (small)",
        price: 18000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Waist to knee length (small)",
        price: 23000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Bob to shoulder length (smedium)",
        price: 13000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Bra to waist length (smedium)",
        price: 15000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Waist to knee length (smedium)",
        price: 20000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Bob to shoulder length (medium)",
        price: 12000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Bra to waist length (medium)",
        price: 14000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Waist to knee length (medium)",
        price: 19000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Bra to waist length (large)",
        price: 14000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Waist to knee length (large)",
        price: 18000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Bra to waist length (jumbo)",
        price: 12000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Waist to knee length (jumbo)",
        price: 16000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Bob to shoulder length (extra small)",
        price: 20000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Bra to waist length (extra small)",
        price: 30000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Waist to knee length (extra small)",
        price: 35000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
    ],
  },
  {
    category: "Stitched Cornrow Braids",
    description: "",
    items: [
      {
        name: "2-4 stitched cornrows",
        price: 7000,
        link: "/book/calendly",
        desc: "Be it a plain stitch straight braids, the ends rolled up, curled, etc. ",
        displayPricePrefix: "",
      },
      {
        name: "6 stitched cornrows",
        price: 10000,
        link: "/book/calendly",
        desc: "Be it a plain stitch straight braids, the ends rolled up, curled, etc. ",
        displayPricePrefix: "",
      },
      {
        name: "8 stitched cornrows",
        price: 12000,
        link: "/book/calendly",
        desc: "Be it a plain stitch straight braids, the ends rolled up, curled, etc. ",
        displayPricePrefix: "",
      },
      {
        name: "10 stitched cornrows",
        price: 14000,
        link: "/book/calendly",
        desc: "Be it a plain stitch straight braids, the ends rolled up, curled, etc. ",
        displayPricePrefix: "",
      },
      {
        name: "12 stitched cornrows",
        price: 16000,
        link: "/book/calendly",
        desc: "Be it a plain stitch straight braids, the ends rolled up, curled, etc. ",
        displayPricePrefix: "",
      },
      {
        name: "14+ stitched cornrows",
        price: 18000,
        link: "/book/calendly",
        desc: "Be it a plain stitch straight braids, the ends rolled up, curled, etc. ",
        displayPricePrefix: "",
      },
    ],
  },
  {
    category: "Locs",
    description: "",
    items: [
      {
        name: "Butterfly locs",
        price: 15000,
        link: "/book/calendly",
        desc: "Depending on the length and size of the locs. ",
        displayPricePrefix: "From",
      },
      {
        name: "Invincible locs",
        price: 15000,
        link: "/book/calendly",
        desc: "Depending on the length and size of the locs. ",
        displayPricePrefix: "From",
      },
      {
        name: "Locs retwist/touchup",
        price: 8000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "From",
      },
      {
        name: "New dreadlocks",
        price: 25000,
        link: "/book/calendly",
        desc: "Permanently locking your hair, starting your loc journey from scratch. ",
        displayPricePrefix: "From",
      },
      {
        name: "Faux locs/faux dreadlocks",
        price: 10000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "From",
      },
    ],
  },
  {
    category: "Hair installation and styling.",
    description: "",
    items: [
      {
        name: "Frontal installation (Virgin install)",
        price: 25000,
        link: "/book/calendly",
        desc: "For a new wig. ",
        displayPricePrefix: "",
      },
      {
        name: "Frontal installation (reinstall)",
        price: 20000,
        link: "/book/calendly",
        desc: "For a previously installed wig. ",
        displayPricePrefix: "",
      },
      {
        name: "5 by 5 or mini frontals",
        price: 15000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "360 wig installation (Virgin install)",
        price: 35000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "360 wig installation (re-install)",
        price: 30000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "My hairstyle is not on the list",
        price: 0,
        link: "/book/calendly",
        desc: "Specific new/trendy hairstyles like some weaving styles, two steps, lemonade braids, chain twists, etc, are not included due to the ambiguity of the hairstyle (i.e they come in different designs/patterns). Select this option and proceed with your booking following the steps. On your booking confirmation page you’ll see our WhatsApp link below. Click on it, tell/send us the style you want to make in your preferred length after sending in your deposit fee receipt and we will respond to you as soon as possible. ",
        displayPricePrefix: "",
      },
    ],
  },
  {
    category: "Other Services",
    description: "",
    items: [
      {
        name: "Hair relaxing",
        price: 6000,
        link: "/book/calendly",
        desc: "Perming/retouching your hair, Relaxer included. ",
        displayPricePrefix: "",
      },
      {
        name: "Hair steaming treatment",
        price: 15000,
        link: "/book/calendly",
        desc: "Hair breakage occurs when your hair is moisture deprived. No amount of protective hairstyles can stop the breakage. Therefore its very important to keep a consistent moisture level to avaoid hair breakage by regularly steaming your hair. ",
        displayPricePrefix: "From",
      },
      {
        name: "Hair wash and blowout",
        price: 3000,
        link: "/book/calendly",
        desc: "Blow out is complementary and not compulsory. You can choose to just wash and dry. ",
        displayPricePrefix: "",
      },
      {
        name: "Hair trimming",
        price: 3000,
        link: "/book/calendly",
        desc: "Trimming off your hair's split ends promotes good and faster hair growth. Makes your hair really healthy and prevents further breakage. ",
        displayPricePrefix: "From",
      },
      {
        name: "Silk press",
        price: 10000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
    ],
  },
  {
    category: "Ad Ons",
    description: "",
    items: [
      {
        name: "Wig revamping and styling",
        price: 10000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Closure or frontal lace repair",
        price: 10000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "From",
      },
      {
        name: "Hair wigging for closure wigs",
        price: 10000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "Hair wigging for frontal wigs",
        price: 12000,
        link: "/book/calendly",
        desc: "",
        displayPricePrefix: "",
      },
      {
        name: "VIP private service setup request",
        price: 5000,
        link: "/book/calendly",
        desc: "For our clients seeking a bit of privacy while get their hair done or simply to work in a private environment whilst getting their hair done ",
        displayPricePrefix: "",
      },
    ],
  },
];
